// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hcbpypaasoibqnhbxkqs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhjYnB5cGFhc29pYnFuaGJ4a3FzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjA5MTgxOTUsImV4cCI6MjA3NjQ5NDE5NX0.D54kWrUn96H1FLnjUzQbCy3eASNjEVLSBQpfHPhrLCw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});